kind: pipeline
type: docker
name: am-micro

steps:
- name: build
  image: registry.holygrail.com:5000/golang:1.17
  commands:
  - make build
  when:
    branch:
      - v1.0
    event:
      include:
      - push
      - pull_request

- name: docker-build
  image: plugins/docker
  settings:
    repo: registry.holygrail.com:5000/am-micro
    registry: registry.holygrail.com:5000
    insecure: true
    mirror: https://docker.mirrors.ustc.edu.cn/
  when:
    branch:
      - v1.0
    event:
      include:
      - push
      - pull_request

- name: deploy_archer
  image: appleboy/drone-ssh
  settings:
    host: archer.holygrail.com
    username:
      from_secret: archer_docker_user
    password:
      from_secret: archer_docker_password
    script:
      - docker stop am-downloader am-downloadmanager am-spider-dmhy am-spider-nyaa am-spider-miobt am-spider-bangumi
      - docker rm am-downloader am-downloadmanager am-spider-dmhy am-spider-nyaa am-spider-miobt am-spider-bangumi
      - docker rmi registry.holygrail.com:5000/am-micro:latest
      - docker-compose -f /store/config/docker-compose/archer/docker-compose.yml up -d am-downloader am-downloadmanager am-spider-dmhy am-spider-nyaa am-spider-miobt am-spider-bangumi
  when:
    branch:
      - v1.0
    event:
    - promote
    target:
    - archer

trigger:
  branch:
  - v1.0