kind: pipeline
type: docker
name: am

steps:
- name: build
  image: registry.holygrail.com:5000/golang:1.17
  commands:
  - go build -mod vendor -o am 
  when:
    branch:
      - master
    event:
      include:
      - push
      - pull_request

- name: docker-build
  image: plugins/docker
  settings:
    repo: registry.holygrail.com:5000/am
    registry: registry.holygrail.com:5000
    insecure: true
    mirror: https://docker.mirrors.ustc.edu.cn/
  when:
    branch:
      - master
    event:
      include:
      - push
      - pull_request

- name: deploy_archer
  image: appleboy/drone-ssh
  settings:
    host: archer.holygrail.com
    username:
      from_secret: archer_docker_user
    password:
      from_secret: archer_docker_password
    script:
      - docker stop am
      - docker rm am
      - docker rmi registry.holygrail.com:5000/am:latest
      - docker pull registry.holygrail.com:5000/am:latest
      - docker-compose -f /store/config/docker-compose/archer/docker-compose.yml up -d am
  when:
    event:
    - promote
    target:
    - archer

trigger:
  branch:
  - master