kind: pipeline
type: docker
name: am-micro

steps:
- name: build
  image: registry.holygrail.com:5000/golang:1.17
  commands:
  - make build
  trigger:
    branch:
      - v1.0
    event:
      include:
      - push
      - pull_request

- name: docker-build
  image: plugins/docker
  settings:
    repo: registry.holygrail.com:5000/am-micro
    registry: archer.holygrail.com:5000
    auto_tag: true
    insecure: true
    mirror: http://hub-mirror.c.163.com
  trigger:
    branch:
      - v1.0
    event:
      include:
      - push
      - pull_request

- name: deploy_archer
  image: appleboy/drone-ssh
  settings:
    host: am.holygrail.com
    username:
      from_secret: docker_user
    password:
      from_secret: docker_password
    script:
      - docker stop am-micro
      - docker rm am-micro
      - docker rmi archer.holygrail.com:5000/am-micro:latest
      - docker pull archer.holygrail.com:5000/am-micro:latest
      - docker-compose -f /usb/config/docker-compose/archer/docker-compose.yml up -d
  trigger:
    branch:
      - v1.0
    event:
    - promote
    target:
    - archer