kind: pipeline
type: docker
name: am

steps:
- name: build
  image: golang
  commands:
  - go build -o am 

- name: docker-build
  image: plugins/docker
  settings:
    repo: archer.holygrail.com:5000/am
    registry: archer.holygrail.com:5000
    auto_tag: true
    insecure: true
    mirror: http://hub-mirror.c.163.com

trigger:
  branch:
  - master
  event:
  - push