kind: pipeline
type: docker
name: am

steps:
- name: build
  image: golang
  commands:
  - go build -mod vendor -o am 

- name: docker-build
  image: plugins/docker
  settings:
    repo: archer.holygrail.com:5000/am
    registry: archer.holygrail.com:5000
    auto_tag: true
    insecure: true
    mirror: http://hub-mirror.c.163.com
  when:
    event:
    - promote

- name: deploy
  image: appleboy/drone-ssh
  settings:
    host: archer.holygrail.com
    username:
      from_secret: docker_user
    password:
      from_secret: docker_password
    script:
      - docker pull archer.holygrail.com:5000/am:latest
      - docker-compose -f /usb/config/docker-compose/docker-compose.yml up -d
  when:
    event:
    - promote
    target:
    - archer

trigger:
  branch:
  - master
  event:
  - push
  - promote