// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-kratos/kratos/v2/registry"
	"github.com/staroffish/am/app/downloader/internal/biz"
	"github.com/staroffish/am/app/downloader/internal/conf"
	"github.com/staroffish/am/app/downloader/internal/data"
	"github.com/staroffish/am/app/downloader/internal/server"
	"github.com/staroffish/am/app/downloader/internal/service"
	"github.com/staroffish/am/common/config"
	"github.com/staroffish/am/common/util"
	"go.etcd.io/etcd/client/v3"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(configComponentName config.ComponentName, client *clientv3.Client, logger log.Logger, registrar registry.Registrar) (*kratos.App, func(), error) {
	httpServerConfig, err := config.NewHTTPServerConfig(client, configComponentName)
	if err != nil {
		return nil, nil, err
	}
	grpcServerConfig, err := config.NewGrpcServerConfig(client, configComponentName)
	if err != nil {
		return nil, nil, err
	}
	reidsConfig, err := config.NewRedisConfig(client)
	if err != nil {
		return nil, nil, err
	}
	downloaderServerConfig := conf.NewDownloaderServerConfig(httpServerConfig, grpcServerConfig, reidsConfig)
	redisClient, err := util.NewReidsClient(reidsConfig)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(downloaderServerConfig, redisClient, client, logger)
	if err != nil {
		return nil, nil, err
	}
	downloaderConfig := conf.NewDownloaderConfig(client, configComponentName, logger)
	downloaderRepo, err := data.NewDownloadRepo(dataData, downloaderConfig, configComponentName, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	downloader := biz.NewDownloader(downloaderRepo, logger)
	downloaderService := service.NewDownloaderService(downloader)
	httpServer := server.NewHTTPServer(downloaderServerConfig, downloaderService, logger)
	grpcServer := server.NewGRPCServer(downloaderServerConfig, downloaderService, logger)
	app := newApp(logger, httpServer, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
