// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.1.4

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type AmspiderHTTPServer interface {
	Crawl(context.Context, *CrawlRequest) (*CrawlResponse, error)
}

func RegisterAmspiderHTTPServer(s *http.Server, srv AmspiderHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/crawl", _Amspider_Crawl0_HTTP_Handler(srv))
}

func _Amspider_Crawl0_HTTP_Handler(srv AmspiderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CrawlRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.amspider.v1.Amspider/Crawl")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Crawl(ctx, req.(*CrawlRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CrawlResponse)
		return ctx.Result(200, reply)
	}
}

type AmspiderHTTPClient interface {
	Crawl(ctx context.Context, req *CrawlRequest, opts ...http.CallOption) (rsp *CrawlResponse, err error)
}

type AmspiderHTTPClientImpl struct {
	cc *http.Client
}

func NewAmspiderHTTPClient(client *http.Client) AmspiderHTTPClient {
	return &AmspiderHTTPClientImpl{client}
}

func (c *AmspiderHTTPClientImpl) Crawl(ctx context.Context, in *CrawlRequest, opts ...http.CallOption) (*CrawlResponse, error) {
	var out CrawlResponse
	pattern := "/v1/crawl"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.amspider.v1.Amspider/Crawl"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
