// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: api/spider/v1/spider.proto

package v1

import (
	context "context"
	common "github.com/staroffish/am/api/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SpiderClient is the client API for Spider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpiderClient interface {
	Crawl(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*CrawlResponse, error)
}

type spiderClient struct {
	cc grpc.ClientConnInterface
}

func NewSpiderClient(cc grpc.ClientConnInterface) SpiderClient {
	return &spiderClient{cc}
}

func (c *spiderClient) Crawl(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*CrawlResponse, error) {
	out := new(CrawlResponse)
	err := c.cc.Invoke(ctx, "/api.spider.v1.Spider/Crawl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpiderServer is the server API for Spider service.
// All implementations must embed UnimplementedSpiderServer
// for forward compatibility
type SpiderServer interface {
	Crawl(context.Context, *common.Empty) (*CrawlResponse, error)
	mustEmbedUnimplementedSpiderServer()
}

// UnimplementedSpiderServer must be embedded to have forward compatible implementations.
type UnimplementedSpiderServer struct {
}

func (UnimplementedSpiderServer) Crawl(context.Context, *common.Empty) (*CrawlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Crawl not implemented")
}
func (UnimplementedSpiderServer) mustEmbedUnimplementedSpiderServer() {}

// UnsafeSpiderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpiderServer will
// result in compilation errors.
type UnsafeSpiderServer interface {
	mustEmbedUnimplementedSpiderServer()
}

func RegisterSpiderServer(s grpc.ServiceRegistrar, srv SpiderServer) {
	s.RegisterService(&Spider_ServiceDesc, srv)
}

func _Spider_Crawl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiderServer).Crawl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.spider.v1.Spider/Crawl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiderServer).Crawl(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Spider_ServiceDesc is the grpc.ServiceDesc for Spider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Spider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.spider.v1.Spider",
	HandlerType: (*SpiderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Crawl",
			Handler:    _Spider_Crawl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/spider/v1/spider.proto",
}
