// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/registry"
	"github.com/staroffish/am/app/downloadmanager/internal/biz"
	"github.com/staroffish/am/app/downloadmanager/internal/conf"
	"github.com/staroffish/am/app/downloadmanager/internal/data"
	"github.com/staroffish/am/app/downloadmanager/internal/server"
	"github.com/staroffish/am/app/downloadmanager/internal/service"
	"github.com/staroffish/am/common/config"
	"github.com/staroffish/am/common/util"
	"go.etcd.io/etcd/client/v3"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(configComponentName config.ComponentName, version config.Version, client *clientv3.Client, registrar registry.Registrar, taskEtcdPrefix util.TaskEtcdPrefix, discovery registry.Discovery) (*kratos.App, func(), error) {
	logger, err := util.NewLogger(client, configComponentName, version)
	if err != nil {
		return nil, nil, err
	}
	httpServerConfig, err := config.NewHTTPServerConfig(client, configComponentName)
	if err != nil {
		return nil, nil, err
	}
	grpcServerConfig, err := config.NewGrpcServerConfig(client, configComponentName)
	if err != nil {
		return nil, nil, err
	}
	reidsConfig, err := config.NewRedisConfig(client)
	if err != nil {
		return nil, nil, err
	}
	downloadManagerServerConfig := conf.NewDownloadManagerServerConfig(httpServerConfig, grpcServerConfig, reidsConfig)
	dataData, cleanup, err := data.NewData(downloadManagerServerConfig, client, logger)
	if err != nil {
		return nil, nil, err
	}
	etcdWatcher := util.NewEtcdWatcher(client, taskEtcdPrefix, logger)
	downloadTask := data.NewDownloadTask(dataData, taskEtcdPrefix, etcdWatcher, logger)
	downloaderClient := data.NewDownloaderClient(discovery)
	downloadManagerRepo := data.NewDownloadManagerRepo(dataData, downloadTask, downloaderClient, logger)
	downloadManager := biz.NewDownloadManager(downloadManagerRepo, logger)
	downloadmanagerService := service.NewDownloadmanagerService(downloadManager, logger)
	httpServer := server.NewHTTPServer(downloadManagerServerConfig, downloadmanagerService, logger)
	grpcServer := server.NewGRPCServer(downloadManagerServerConfig, downloadmanagerService, logger)
	app := newApp(logger, httpServer, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
